# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 04:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=32)),
                ('payment_type', models.CharField(max_length=255, null=True)),
                ('payment_hash', models.CharField(max_length=255, null=True)),
                ('payment_data', models.CharField(max_length=32, null=True)),
                ('shipping_info', models.CharField(max_length=255, null=True)),
                ('shipping', models.BooleanField(verbose_name='is shipping?')),
                ('insured', models.BooleanField(default=False, verbose_name='is insured?')),
                ('insurance', models.IntegerField(default=0)),
                ('br_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Card name')),
                ('expiry', models.CharField(blank=True, max_length=10, null=True, verbose_name='Card expiry')),
                ('printed_qty', models.IntegerField(default=0)),
                ('delivery', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shows.Delivery')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item_data', models.CharField(max_length=255, null=True)),
                ('price_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.PriceCategory')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.ManyToManyField(related_name='items', through='purchase.PurchaseItem', to='shows.PriceCategory'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Performance'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
