# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0025_auto_20160320_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='enquiry'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('PE', 'Pending'), ('CL', 'Closed')], default='OP', max_length=2),
        ),
        migrations.AlterField(
            model_name='thread',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('PE', 'Pending'), ('CL', 'Closed')], default='OP', max_length=2),
        ),
        migrations.AlterField(
            model_name='topicfield',
            name='field_type',
            field=models.CharField(choices=[('email', 'email'), ('text', 'text'), ('file', 'file')], max_length=50),
        ),
    ]
