# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 04:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='INT', editable=False, max_length=32, verbose_name='season')),
                ('account', models.PositiveIntegerField(editable=False, help_text='Set by Softix', verbose_name='account')),
                ('atype', models.PositiveSmallIntegerField(blank=True, help_text='Set by Softix', null=True, verbose_name='account type')),
                ('area_code', models.CharField(blank=True, max_length=32, verbose_name='area code')),
                ('home_phone', models.CharField(max_length=32, verbose_name='home phone')),
                ('other_phone', models.CharField(blank=True, max_length=32, verbose_name='other phone')),
                ('name1', models.CharField(blank=True, max_length=32, verbose_name='first name')),
                ('name2', models.CharField(blank=True, max_length=32, verbose_name='middle name')),
                ('name3', models.CharField(max_length=32, verbose_name='last name')),
                ('name4', models.CharField(blank=True, max_length=32, verbose_name='other name')),
                ('name5', models.CharField(blank=True, max_length=32, verbose_name='other name')),
                ('addr1', models.CharField(blank=True, max_length=34, verbose_name='address line 1')),
                ('addr2', models.CharField(blank=True, max_length=34, verbose_name='address line 2')),
                ('addr3', models.CharField(blank=True, max_length=34, verbose_name='address line 3')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='city')),
                ('zip', models.CharField(blank=True, max_length=16, verbose_name='zip/postal code')),
                ('countrycode', models.CharField(blank=True, max_length=250, verbose_name='country')),
                ('apartment', models.CharField(blank=True, max_length=16, verbose_name='apartment number')),
                ('housenumber', models.CharField(blank=True, max_length=16, verbose_name='house number')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='comment')),
                ('email_addr', models.EmailField(max_length=254, verbose_name='email address')),
                ('site_attrib', models.BooleanField(verbose_name='arbitrary boolean flag - for internal usage')),
                ('do_not_mail', models.BooleanField(verbose_name='do not mail')),
                ('dead_account', models.BooleanField(verbose_name='dead account')),
                ('left_address', models.BooleanField(verbose_name='inaccurate address')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, verbose_name='gender')),
                ('member_dob', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('member_since', models.DateField(blank=True, default=datetime.date.today, editable=False, null=True, verbose_name='member since')),
                ('primary_season', models.CharField(blank=True, max_length=32, verbose_name='primary season')),
                ('primary_an', models.PositiveIntegerField(blank=True, null=True, verbose_name='primary account')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('season', 'account')]),
        ),
    ]
